### ISSUE TITLE
Exposed Security Key

### ISSUE THREAD

**Issue by LiamCJ** [ovieokeh/react-stripe-payment#3]
I have reading through your tutorial [building-payments-system-react-stripe](https://blog.logrocket.com/building-payments-system-react-stripe/) for a project and it has been very helpful so far, and when running your app, after downloading it from github, i noticed you left your security key in the code, i don't know if it was a mistake or you did it on purpose but i thought i'd let you know anyway since

**Comment by ovieokeh** [comment]
Thanks, it's a [publishable key](https://stripe.com/docs/keys) so there's no harm having it committed.
